// <auto-generated />
using Alcatraz.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alcatraz.Context.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20210810200359_AddFriendships")]
    partial class AddFriendships
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("Alcatraz.Context.Entities.Relationship", b =>
                {
                    b.Property<uint>("User1Id")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("User2Id")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ByRelationShip")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("User1Id", "User2Id");

                    b.HasIndex("User2Id");

                    b.ToTable("UserRelationships");
                });

            modelBuilder.Entity("Alcatraz.Context.Entities.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameNickName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Alcatraz.Context.Entities.Relationship", b =>
                {
                    b.HasOne("Alcatraz.Context.Entities.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alcatraz.Context.Entities.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });
#pragma warning restore 612, 618
        }
    }
}
