namespace Blaze3SDK.Blaze.Authentication
{
	public enum StatusReason : int
	{
		UNKNOWN = 0,
		NONE = 1,
		REACTIVATED_CUSTOMER = 2,
		INVALID_EMAIL = 3,
		PRIVACY_POLICY = 4,
		PARENTS_REQUEST = 5,
		PARENTAL_REQUEST = 6,
		SUSPENDED_MISCONDUCT_GENERAL = 7,
		SUSPENDED_MISCONDUCT_HARASSMENT = 8,
		SUSPENDED_MISCONDUCT_MACROING = 9,
		SUSPENDED_MISCONDUCT_EXPLOITATION = 10,
		CUSTOMER_OPT_OUT = 11,
		CUSTOMER_UNDER_AGE = 12,
		EMAIL_CONFIRMATION_REQUIRED = 13,
		MISTYPED_ID = 14,
		ABUSED_ID = 15,
		DEACTIVATED_EMAIL_LINK = 16,
		DEACTIVATED_CS = 17,
		CLAIMED_BY_TRUE_OWNER = 18,
		BANNED = 19,
	}
}
