namespace Blaze3SDK.Blaze.Util
{
	public enum FilterResult : int
	{
		FILTER_RESULT_PASSED = 0,
		FILTER_RESULT_OFFENSIVE = 1,
		FILTER_RESULT_UNPROCESSED = 2,
		FILTER_RESULT_STRING_TOO_LONG = 3,
		FILTER_RESULT_OTHER = 4,
	}
}
