namespace Blaze3SDK.Blaze
{
	public enum ClientType : int
	{
		CLIENT_TYPE_GAMEPLAY_USER = 0,
		CLIENT_TYPE_HTTP_USER = 1,
		CLIENT_TYPE_DEDICATED_SERVER = 2,
		CLIENT_TYPE_TOOLS = 3,
		CLIENT_TYPE_INVALID = 4,
	}
}
