namespace Blaze3SDK.Blaze.GameManager
{
	public enum DatalessContext : int
	{
		CREATE_GAME_SETUP_CONTEXT = 0,
		JOIN_GAME_SETUP_CONTEXT = 1,
		INDIRECT_JOIN_GAME_FROM_QUEUE_SETUP_CONTEXT = 2,
		INDIRECT_JOIN_GAME_FROM_RESERVATION_CONTEXT = 3,
		HOST_INJECTION_SETUP_CONTEXT = 4,
	}
}
