namespace Blaze3SDK.Blaze.GameManager
{
	public enum JoinMethod : int
	{
		JOIN_BY_BROWSING = 1,
		JOIN_BY_MATCHMAKING = 2,
		JOIN_BY_INVITES = 4,
		JOIN_BY_PLAYER = 8,
		SYS_JOIN_BY_FOLLOWLEADER_CREATEGAME = 15,
		SYS_JOIN_BY_RESETDEDICATEDSERVER = 16,
		SYS_JOIN_BY_FOLLOWLEADER_RESETDEDICATEDSERVER = 32,
		SYS_JOIN_BY_FOLLOWLEADER_CREATEGAME_HOST = 64,
	}
}
