namespace QuazalServer.RDVServices.GameServices.PCGROnlineServices
{
    public enum RMCProtocolId
    {
        NATTraversalRelayProtocol = 3,
        AuthenticationService = 10,
        SecureService = 11,
        GlobalNotificationEventProtocol = 14,
        MatchMakingService = 21,
        MessageDeliveryProtocol = 27,
        TelemetryService = 36,
        AMMGameClientService = 101,
        AMMDedicatedServerService = 102,
        PlayerProfileService = 103,
        ArmorService = 104,
        InventoryService = 105,
        LootService = 106,
        WeaponService = 107,
        FriendsService = 108,
        ChatService = 110,
        MissionService = 111,
        PartyService = 112,
        RegistrationService = 113,
        StatisticsService = 114,
        AchievementsService = 115,
        ProgressionService = 116,
        DBGTelemetryService = 117,
        RewardService = 118,
        StoreService = 119,
        AdvertisementsService = 121,
        SkillsService = 122,
        LoadoutService = 123,
        TrackingService = 124,
        UnlockService = 125,
        AvatarService = 126,
        WeaponProficiencyService = 127,
        OpsProtocolService = 128,
        ProfilerService = 129,
        ServerInfoService = 130,
        LeaderboardService = 131,
        PveArchetypeService = 133,
        InboxMessageService = 134,
        ProfanityFilterService = 135,
        InspectPlayerService = 136,
        AbilityService = 137,
        SurveyService = 139,
        LeaderboardProtocolService = 5000,
        RPNEProtocolService = 5001,
        OverlordNewsProtocolService = 5002,
        OverlordCoreProtocolService = 5003,
        ExtraContentProtocolService = 5004,
        OverlordFriendsProtocolService = 5005,
        OverlordAwardsProtocolService = 5006,
        OverlordChallengeProtocolService = 5007,
        OverlordDareProtocolService = 5008,
    }
}