namespace QuazalServer.RDVServices.GameServices.PS3DriverServices
{
    public enum RMCProtocolId
    {
        RemoteLogDeviceService = 1,
        NATTraversalService = 3,
        TicketGrantingService = 10,
        SecureConnectionService = 11,
        NotificationEventManager = 14,
        NotificationService = 15,
        HealthService = 18,
        MonitoringService = 19,
        FriendsService = 20,
        MatchMakingService = 21,
        MessagingService = 23,
        PersistentStoreService = 24,
        AccountManagementService = 25,
        MessageDeliveryService = 27,
        UbiAccountManagementService = 29,
        NewsService = 31,
        UbiNewsService = 33,
        PrivilegesService = 35,
        Tracking3 = 36,
        LocalizationService = 39,
        GameSessionService = 42,
        MatchMakingProtocolExtClient = 50,
        OfflineGameNotificationsService = 71,
        NpFriendsService = 83,
        LadderHelperProtocol = 107,
        PlayerStatsService = 108,
        RichPresenceService = 109,
        ClansService = 110,
        MissionService = 111,
        MetaSessionService = 112,
        GameInfoService = 113,
        ContactsExtensionsService = 114,
        UbiMatchmakingService = 115,
        AchievementsService = 116,
        PartyService = 117,
        DriverUniqueIDService = 118,
        SocialNetworksService = 119,
        UbiWinService = 120,
        DriverG2WService = 121,
        Game2WebService = 122,
        GameSessionExService = 123,
        OverlordCoreProtocolService = 5003,
        OverlordFriendsService = 5005,
    }
}
