namespace Blaze3SDK.Blaze.Playgroups
{
	public enum PlaygroupMemberRemoveReason : int
	{
		PLAYGROUP_MEMBER_REMOVE_REASON_DEFAULT = 0,
		PLAYGROUP_MEMBER_REMOVE_REASON_DISCONNECTED = 1,
		PLAYGROUP_MEMBER_REMOVE_REASON_KICKED = 2,
		PLAYGROUP_MEMBER_REMOVE_TITLE_BASE_REASON = 3,
	}
}
