namespace Blaze3SDK.Blaze.Authentication
{
	public enum ExternalRefType : int
	{
		BLAZE_EXTERNAL_REF_TYPE_UNKNOWN = 0,
		BLAZE_EXTERNAL_REF_TYPE_XBOX = 1,
		BLAZE_EXTERNAL_REF_TYPE_PS3 = 2,
		BLAZE_EXTERNAL_REF_TYPE_WII = 3,
		BLAZE_EXTERNAL_REF_TYPE_MOBILE = 4,
		BLAZE_EXTERNAL_REF_TYPE_LEGACYPROFILEID = 5,
		BLAZE_EXTERNAL_REF_TYPE_TWITTER = 6,
		BLAZE_EXTERNAL_REF_TYPE_FACEBOOK = 7,
	}
}
