namespace Blaze3SDK.Blaze.Clubs
{
	public enum MemberOnlineStatus : int
	{
		CLUBS_MEMBER_OFFLINE = 0,
		CLUBS_MEMBER_ONLINE_INTERACTIVE = 1,
		CLUBS_MEMBER_ONLINE_NON_INTERACTIVE = 2,
		CLUBS_MEMBER_IN_GAMEROOM = 3,
		CLUBS_MEMBER_IN_OPEN_SESSION = 4,
		CLUBS_MEMBER_IN_GAME = 5,
		CLUBS_MEMBER_CUSTOM_ONLINE_STATUS = 6,
	}
}
